# Generated by Django 5.2 on 2025-04-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_module_question_recommendation_useranswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
