# Generated by Django 5.2 on 2025-05-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_usertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
