# Generated by Django 5.2 on 2025-05-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lessonquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonquiz',
            options={'managed': False},
        ),
    ]
