# Generated by Django 5.2 on 2025-05-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_lessonquiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'managed': True, 'ordering': ['user_id', 'module_id']},
        ),
        migrations.AlterModelTable(
            name='lessonquiz',
            table='lesson_quizzes',
        ),
    ]
